language: node_js

node_js: stable

after_success:
    - npm run deploy
    - npm run dist

deploy:
    provider: npm
    email: "rrdelaney@outlook.com"
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
        branch: master
        condition: $(npm view redux-reaction dist-tags.latest) != $(node -p "require('./package.json').version")
